name: CI

on:
  - push

env:
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: 123
  POSTGRES_DB: test


jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Instalar dependências
        run: npm ci
      - name: Rodar testes 
        run: npm t
  autodeploy:
    name: Acesso SSH
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Usando ssh
      uses: appleboy/ssh-action@master
      with:
        host: vps18215.publiccloud.com.br
        username: root
        password: ${{ secrets.PASSWORD }}
        port: 22
        script_stop: true
        script: |
          env
          cd sanofiAlmoxarifado
          forever stopall
          git pull
          npm i
          npm run build
          npm run migrate
          forever start dist/src/index.js